#!/bin/sh

git submodule update --init

cd home
for file in .*
do
    echo "file=$file"
    if [ "$file" = "." -o "$file" = ".." ]
    then
        continue
    fi

    ln -s `readlink -f "$file"` ~/"$file"
done
cd -
