#!/bin/sh

git submodule update --init

cd home
for file in .*
do
    if [ "$file" = "." -o "$file" = ".." ]
    then
        continue
    fi

    if [ -h ~/"$file" ]
    then
        echo "$file already a symbolic link."
        continue
    else
        ln -s `readlink -f "$file"` ~/"$file"
    fi
done
cd -
